version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bookstore-db
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: bookstore
    ports:
      - "5433:5432" # Changing the host port to 5433
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env.prod
  app:
    image: mukeshkumararumugam/book-store:latest
    container_name: bookstore-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      logging.level.root: debug
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env.prod

volumes:
  db_data:

networks:
  app-network:
